name: Bio Form (internal)
description: Bio submission form for Hubbers
title: "Bio: [name]"
labels: 'bio'
assignees: shmeadyy

body:
  - type: markdown
    attributes:
       value: |
         Thanks for requesting to be a speaker! We're excited to get to know you and get you ready to share about GitHub at conferences and events!
  
  - id: pronouns
    type: dropdown
    attributes:
      label: Pronouns
      options:
        - "she/her/hers"
        - "he/him/his"
        - "they/them"
    validations:
      required: true
  
  - id: location
    type: input
    attributes:
      label: Location
      description: "What city, state and country do you live in? This is just where you're _primarily_ located so that we can match you with conferences located close to you."
      placeholder: San Francisco, CA, United States
    validations:
      required: true
  
  - id: title
    type: input
    attributes:
      label: Title/Team
      description: "What's your title and the team that you're on? i.e. Product Manager, Planning & Tracking"
    validations:
      required: true
  
  - id: languages
    type: input
    attributes:
      label: Languages
      description: "What languages do you speak? Please only include languages where you are a near fluent speaker (i.e. would feel confident answering questions from the audience about your presentation in that language!)"
    validations: 
      required: true
  
  - id: bio
    type: textarea
    attributes:
      label: Bio
      description: "Conferences often ask for short bios for speakers. Please share a short 2-3 sentence blurb about you!"

  - id: experience
    type: input
    attributes:
      label: How would you rate your speaking experience?
      description: On a scale of 1-5, 1 being novice and 5 being expert
  
  - id: previous-events
    type: checkboxes
    attributes:
      label: What are the types of events you've participated in before?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
